### ISSUE TITLE
投票機能で現在の投票数を表示させて欲しい

### ISSUE THREAD

**Issue by sanao1006** [Kinoshita0623/MisskeyAndroidClient#1842]
## 概要
タイトルの通りです。
Web版のように現在何票投票されているかの表示がmilkteaにもあれば便利かなと思いました(画像赤線部分)。
<img src="https://github.com/pantasystem/Milktea/assets/62137820/0037e290-9323-4827-9b52-032d9368ded8" width="500px">

具体的な実装方法などはまだ考えていないですが、もしこの機能がアリならば実装をしてみたいです！
「結果を見る」や「投票する・投票済み」などの機能はもしこのissueが採用されるなら合わせて実装すべきかもです(issueは分けるべきかも？)

## 追記
いつもmilktea使わせてもらっています！本当に使いやすくて最高です！

**Comment by pantasystem** [comment]
いいですね

**Comment by pantasystem** [comment]
一旦投票件数の実装の方針とか考えてここに書いてもらえますか？

**Comment by sanao1006** [comment]
おおまかですが方針を考えてみました。
最初は`PollListLinearLayoutBinder.bindPollChoices`にコードを書き足す方針で行こうかなと思ったのですが、うまくいかなかったので `PollListLinearLayoutBinder`に新しい関数作って投票件数を表示させる方針にしました

1. `PollListLinearLayoutBinder`にこんな感じの実装の関数`bindVoteResult()`を追加
```kotlin
    fun bindVoteResult(
        layout: LinearLayout,
        totalVoteCount: Int
    ) {
        val binding = ItemVoteResultBinding.inflate(LayoutInflater.from(layout.context), layout, false)

        binding.voteResult.text = layout.context.getString(R.string.total_vote_count, totalVoteCount.toString())
        layout.addView(binding.root)
    }
```
   - features/noteのres/layoutに`item_vote_result.xml`レイアウト追加。左寄せのTextViewのみ設置 (idは`voteResult`)
   - common_resourceのvalues/strings.xmlには`%s votes in total`みたいなstringを追加 (nameは`total_vote_count`)
   - layout.context.getStringで`totalVoteCount`を%sに代入
 
2. `PollHelper`で`PollListLinearLayoutBinder.bindPollChoices`の真下あたりに以下のように実装して画面に投票数を反映させる
```kotlin
PollListLinearLayoutBinder.bindVoteResult(this, poll.totalVoteCount)
```

いちおうこんな感じで実装してみたところ見た目はこんな感じになりました (命名は割と雑かもです)。
<image src="https://github.com/pantasystem/Milktea/assets/62137820/0cc29f78-b9b1-4dac-8631-361c46af8a9b" width="300px">
<image src="https://github.com/pantasystem/Milktea/assets/62137820/f03be2c0-e811-4d93-a66b-3cb1bcb432ed" width="300px">

**Comment by pantasystem** [comment]
良いと思います🙆‍♀

**Comment by pantasystem** [comment]
引き続きよろしくお願いします🙇🙇

**Comment by sanao1006** [comment]
とりあえずPR作成してみました。お手すきの際にご確認お願いします！
