### ISSUE TITLE
投稿が自分の投稿の場合は通報の選択肢を表示しない

### ISSUE THREAD

**Issue by pantasystem** [Kinoshita0623/MisskeyAndroidClient#1869]
# 概要
自分の投稿を報告できる仕様はよくわからないし紛らわしいので
投稿が自分の投稿である場合オプションダイアログに自分の投稿を表示しないようにしたい。

**Comment by pantasystem** [comment]
[この箇所](https://github.com/pantasystem/Milktea/blob/b372947456eabf28a7b42364940e3e9b8b025f06/modules/features/note/src/main/java/net/pantasystem/milktea/note/option/NoteOptionDialogLayout.kt#L207-L213)に分岐を追加するだけで対応できると思います。
判定するための条件は、[NoteOptionUiStateに含まれています](https://github.com/pantasystem/Milktea/blob/b372947456eabf28a7b42364940e3e9b8b025f06/modules/features/note/src/main/java/net/pantasystem/milktea/note/option/NoteOptionViewModel.kt#L122-L122)

**Comment by sanao1006** [comment]
このissue対応したいです！
`uiState: NoteOptionUiState`の`isMyNote`がfalseのときだけ通報の選択肢を表示させるようにすればいけそうです👍

**Comment by pantasystem** [comment]
お願いします🙇
