### ISSUE TITLE
フォロー、フォロワー、一覧画面のグリッド表示化

### ISSUE THREAD

**Issue by pantasystem** [Kinoshita0623/MisskeyAndroidClient#1872]
# 概要
現状フォロー・フォロワー一覧はLazyColumnで実装しているので、
タブレットなどの画面サイズが大きい端末では一つの要素が無駄に横に長く表示されてしまう。
なので[Lazyグリッド](https://developer.android.com/jetpack/compose/lists?hl=ja#lazy-grids)を用いて、一定画面サイズ以上の場合はグリッドで表示されるようにしたい。

**Comment by pantasystem** [comment]
この部分です
https://github.com/pantasystem/Milktea/blob/b372947456eabf28a7b42364940e3e9b8b025f06/modules/features/user/src/main/java/net/pantasystem/milktea/user/compose/UserDetailCardPageableList.kt#L37-L37

**Comment by pantasystem** [comment]
UserDetailCardの高さは不定だけど正しく表示できるんだろうか🤔

**Comment by sanao1006** [comment]
アサインお願いします！

**Comment by pantasystem** [comment]
しました
よろしくお願いします🙇

**Comment by sanao1006** [comment]
ちらっとしかまだ触ってませんがイメージ的にはこんな感じにUserDetailCardが何列か(画像では2列)で縦に続いていく感じですかね？


https://github.com/pantasystem/Milktea/assets/62137820/c533f4dd-3fb7-46be-a89c-434f3760025e

**Comment by pantasystem** [comment]
イメージとしては画面の横幅に応じて列数が増えるイメージですね
Lazy Grid Adaptiveをイメージしてます
