### ISSUE TITLE
つながりの公開範囲が非公開のユーザーのフォローフォロワー一覧画面を見るとエラー文が表示される

### ISSUE THREAD

**Issue by sanao1006** [Kinoshita0623/MisskeyAndroidClient#1877]
## 不具合の概要
タイトルの条件下でフォロー、フォロワーの一覧画面を表示するとエラー文が表示される
<image src="https://github.com/pantasystem/Milktea/assets/62137820/202294cc-f560-402d-aa90-88b1cc33c6c3" width="300"></image>
## 再現方法
- つながりの公開範囲が「非公開」のユーザーのユーザー詳細画面へ移動する
- フォローフォロワーの一覧画面を見ると画像のようなエラー文が表示されてしまう
## 期待する動作（２案）
1.  何も表示させないもしくは「いません！」みたいな文言を置く
2.  そもそもつながりの公開範囲が非表示のユーザーはweb版と同様にフォローとフォロワーの導線を表示させない(以下web版画像)

全範囲公開 | 非表示
:--: | :--:
|<image src="https://github.com/pantasystem/Milktea/assets/62137820/b54ca83a-d167-447c-afac-3658e64044e5" width="300"></image>|<image src="https://github.com/pantasystem/Milktea/assets/62137820/a6ace8ff-aa97-4250-8e9a-8aaf2f4f78b8" width="300"></image>|

## 不具合が発生した時の端末
 - Device: Google Pixel 6a
 - OS Version: Tiramisu
 - App Version: 34
と
 - Device: Pixel Tablet
 - OS Version: UpsideDownCake
 - App Version: 34

**Comment by pantasystem** [comment]
いつの間にかffVisibilityという仕様が追加されてたんですね・・・

**Comment by sanao1006** [comment]
これって結構新しい機能なんですね(次々とアップデートが入るから大変そうです😰)
どうしましょうか？

**Comment by pantasystem** [comment]
対応させるにはMilktea自体のデータベースに変更を加える必要があるのと
それが少しだけ面倒なので
一旦はエラーコードが[Forbidden](https://github.com/pantasystem/Milktea/blob/10b5f4444c4e88dcede511bc5d8f359388a8d459/modules/common/src/main/java/net/pantasystem/milktea/common/errors.kt#L114-L114)の時は「表示する権限がありません」のような
ある程度親切なエラーメッセージを表示するようにするのがいいかもしれませんね
ffVisibilityの対応はすぐに対応する気はないですね・・・
