### ISSUE TITLE
チャンネル一覧以外からチャンネル詳細画面に入った時ヘッダーの戻るボタンが動かない

### ISSUE THREAD

**Issue by sanao1006** [Kinoshita0623/MisskeyAndroidClient#1885]
## 不具合の概要
チャンネル一覧以外からチャンネル詳細画面に入った時ヘッダーの戻るボタンが動かない

## 再現方法
- ユーザー詳細画面やタイムラインやハイライト、通知からチャンネルに投稿された適当なノートを見つける
- チャンネル名をタップしてチャンネル詳細画面へ移動する
- ヘッダーの戻るボタンをタップする
## 期待する動作(2案)
戻るボタンを押すと
1. チャンネル一覧画面へ戻る 
2. （※技術的に可能ならば）チャンネル一覧以外からチャンネル詳細画面に入った時ユーザーならばもともといた画面へ戻る
    - Channelアクティビティをfinishする？
    - ↑これをやるとクラッシュしてうまくいかなかったです...
## Screenshots
**不具合が発生した時のスクリーンショットやキャプチャー**

https://github.com/pantasystem/Milktea/assets/62137820/c145a9e7-689e-4dd2-9836-9839562d9ebe

## 対処案
チャンネル一覧画面へ戻るだけならばChannelActivityのonNavigateUpを
https://github.com/pantasystem/Milktea/blob/09c0b0838f6c72b6416eceac307c582f6e155a79/modules/features/channel/src/main/java/net/pantasystem/milktea/channel/ChannelActivity.kt#L102
`onNavigateUp = { navController.navigate("/channels") }` 
とすれば問題なく動きました。が、コード的には何か微妙な気もします。navigateUp()は動作が微妙だったので止めました。

**Comment by pantasystem** [comment]
確かpopBackStackがBooleanを戻り値として返してくるので
その値で判定できそうだと思ったのですがどうでしょう？

**Comment by sanao1006** [comment]
> 確かpopBackStackがBooleanを戻り値として返してくるので その値で判定できそうだと思ったのですがどうでしょう？

うまくいきました！のちほどPR作成します！

**Comment by pantasystem** [comment]
よろしくお願いします🙇
