### ISSUE TITLE
NotificationFragmentのヘッダの更新ボタンアイコンが分かりづらいかもしれない

### ISSUE THREAD

**Issue by sanao1006** [Kinoshita0623/MisskeyAndroidClient#1889]
## 提案
現在、「通知」のヘッダにある更新ボタンのアイコンが以下の画像のようになっています
![image](https://github.com/pantasystem/Milktea/assets/62137820/1ea4d4fe-6916-4efb-a943-8995fee23b79)
他のアクティビティの更新ボタンのアイコンはすべて（おそらく） ic_refresh_black_24dp を使用しているので、機能的な違いがなければ統一したほうがいいかもしれないと思いました。

## 備考
ic_refresh_black_24dp
![image](https://github.com/pantasystem/Milktea/assets/62137820/541ae86c-0242-4e83-8421-e94cc369de81)

**Comment by pantasystem** [comment]
通知画面のチェックマークはすべての通知に既読をつけるボタンなので、
厳密にはリロードボタンとは異なる意味になっています。

**Comment by sanao1006** [comment]
なるほど、そういうことだったのですね納得しました！

それならば現状のままがよさそうですね

こちら問題なければcloseしますが良いですか？

**Comment by pantasystem** [comment]
Closeする旨承知しました
こちらからCloseします
