### ISSUE TITLE
不明な通知 (type:note)

### ISSUE THREAD

**Issue by hanubeki** [Kinoshita0623/MisskeyAndroidClient#1927]
## 不具合の概要
新着ノートの通知を設定したアカウントが（リ）ノートを投稿した際の通知が「不明な通知」と表示されます。

## 再現方法
* webUIにてアカウントの投稿を通知するように設定する
* 設定したアカウントからの（リ）ノートを受信する

## 期待する動作
「（アカウント）が（リ）ノートを投稿した」旨が表示される

## Screenshots
![Screenshot_20231022-125830](https://github.com/pantasystem/Milktea/assets/6897531/28c66f5e-a860-45fd-82a8-f0e6e7e14577)

## 不具合が発生した時の端末
 - Device: Google Pixel 4a
 - OS Version: Android 13 2023-08-05
 - App Version: v2.146.1

## 備考　
Misskey v2023.10.1

**Comment by hanubeki** [comment]
すいません、 #1915 を確認していませんでした。
重複でしたらクローズしてください。

**Comment by pantasystem** [comment]
ご報告ありがとうございます🙏
この挙動はMisskeyの仕様変更によるもので、
最新のコード自体には反映されています。
先ほど製品版に段階公開を開始したので、反映までしばらくお待ちください🙇
