### ISSUE TITLE
チャンネル内タイムラインで自分のノートをリノートするとチャンネル内ではなくLTLに公開されてしまう不具合

### ISSUE THREAD

**Issue by sanao1006** [Kinoshita0623/MisskeyAndroidClient#1940]
## 不具合の概要
先日何気なくチャンネル内で自分のノートをリノートしたところ、チャンネル内リノートとならずLTLに公開されてしまった。センシティブチャンネルのノートであったため、LTLの方々の心に傷を与えてしまった。

Issue (#1391) をパッと見たところ、チャンネル内のリノートはデフォルトで公開範囲がそのチャンネルになるように指定しているようなので意図した挙動ではない可能性がある
## 再現方法
- チャンネル内タイムラインに入る
- 自分のノートを見つける
- リノートする
## 期待する動作
- チャンネル内でのリノートはLTLに漏れずにチャンネル内タイムラインのみで公開されるようにする。
## 備考　
- 試していないのですが、他人のノートのリノートも漏れるかもしれない？です
- web版のようなチャンネル内リノートや引用が選択肢にあるとよいかもしれない？
![image](https://github.com/pantasystem/Milktea/assets/62137820/53bfcf6f-fa3a-430f-b505-5021edf73209)

# 関連Issue
#1391

**Comment by pantasystem** [comment]
Mastodon対応する時にチャンネル対応の考慮漏れが発生してしまっていたようですね・・・

**Comment by sanao1006** [comment]
めちゃくちゃ迅速な対応ありがとうございます🙇‍♀️
天晴れです！！
