### ISSUE TITLE
一定以上前のバージョンのMisskeyサーバーだとタイムラインが表示できない

### ISSUE THREAD

**Issue by digitalsp** [Kinoshita0623/MisskeyAndroidClient#1945]
## 不具合の概要
自鯖(Misskey v13.6.1ベース)でタイムラインが表示できない

## 再現方法
アプリを起動するとすぐ発生

## 期待する動作
タイムラインを正常に表示できる

## Screenshots
![Screenshot_2023-11-06-06-20-11-795_jp.panta.misskeyandroidclient-edit.jpg](https://github.com/pantasystem/Milktea/assets/82262872/1e574904-221a-44c5-9002-1bc4c0480e6b)

## 不具合が発生した時の端末
 - Device:Xiaomi 13 Ultra
 - OS Version:MIUI Global 14.0.6(TMAEUXM)
 - App Version:v2.151.3

## 備考　
- misskey.ioでは発生しない
- バッジを表示できるようになったタイミングで発生
- エラーが発生している自鯖は、しばらくアップデートしていない

これらのことから、おそらくはバッジがMisskeyのバージョンの違いで正常に取得できていないことが原因であるような気がします

![Screenshot_2023-11-06-17-34-32-507_jp.panta.misskeyandroidclient-edit.jpg](https://github.com/pantasystem/Milktea/assets/82262872/2e793365-388b-4e65-b913-6d307412e2c2)

ちなみに、この問題が発生しても、起動したままバックグラウンドでMilkteaを動かしておくと、起動中に投稿された投稿は正常に表示できます。
バージョンが古いのが悪そうなので、もしよければ古いバージョンのMisskeyサーバーでは、バッジ表示非対応とかにしてでもタイムラインの表示を優先してもらえると助かります```

```

**Comment by pantasystem** [comment]
修正しました。
6c13fde3e3228e9a2192b8470186da0650d97b81

**Comment by pantasystem** [comment]
v2.151.3はオープンベータが対象だったと思うので、オープンベータに最新バージョンを公開しました。
解決が確認んされ次第Closeしたいと思います🙇

**Comment by digitalsp** [comment]
ついさっきv2.151.7が降ってきて、解決が確認できました
ありがとうございます🙇
Closeしてもらって構いません

**Comment by pantasystem** [comment]
ご報告ありがとうございました。
