### ISSUE TITLE
プロフィール画面でそのユーザが誕生日の時は紙吹雪を降らせる

### ISSUE THREAD

**Issue by pantasystem** [Kinoshita0623/MisskeyAndroidClient#1957]
# 概要
下記ライブラリを使って、紙吹雪を降らせてみたい。
xmlとComposeのバージョンがあるが、ComposeはKotlinとのバージョンの依存関係が厳しいので、できればxmlの方を利用したい。
https://github.com/DanielMartinus/Konfetti

**Comment by sanao1006** [comment]
こちらのissue気になっていたのでチャレンジさせてください！

**Comment by pantasystem** [comment]
ぜひよろしくお願いします🙇

**Comment by sanao1006** [comment]
すみません、質問いいですか！

https://github.com/pantasystem/Milktea/commit/b10f402baf16985b685fa3f76f300c09934ead24 このコミットの変な値っていうのはどんな値のことでしょうか？

というのも、UserDetailActivityで`birthday`を出力してみると、誕生日を設定しているユーザーでもnullになっておりbirthdayが取得できていないようで、どうやらここの`@kotlinx.serialization.Transient`が原因みたいだったからです(おそらくですが)

しかし、ここを消すとその変な値の時にまた例外の影響でバグりそうなのでどうすべきか悩んでいます

**Comment by pantasystem** [comment]
少なくともパースできないような変な値のユーザに誕生日が来る可能性は低いので無視でよいかと思います。

**Comment by pantasystem** [comment]
今は知りませんがMisskeyのバージョンによっては99月などを設定できてしまうんですよね
そのようなデータが来るとデコードに失敗してしまうのでデコードに失敗してしまうときにはnullを設定しています。
https://github.com/pantasystem/Milktea/issues/1453

**Comment by pantasystem** [comment]
Transientアノテーションが原因でnullになるのは謎ですね…

**Comment by pantasystem** [comment]
問題なく動作するように修正しました
取り込んでいただけると誕生日を取得できるようになるかと思われます
https://github.com/pantasystem/Milktea/commit/dd15ac064327615283206d86fbe9a80e95d3eb82

**Comment by sanao1006** [comment]
おお！迅速な対応感謝です！！！
