### ISSUE TITLE
CWで注釈を空欄にしてノートするとエラーが発生する

### ISSUE THREAD

**Issue by sanao1006** [Kinoshita0623/MisskeyAndroidClient#1992]
## 不具合の概要
以前までは「内容を隠す」で注釈を空にしたままでも問題なくノートできていたが気づいたらできなくなっていた。
注釈が空のままノートするとエラーが発生する。

## 再現方法
- ノート作成画面へ移動する
- 「内容隠す」ボタンを押する
- 上段の注釈を空にしたままノートする
- エラー発生
## 期待する動作
- 注釈が空の時は「投稿」ボタンを灰色にして使用不可にする
## Screenshots
**不具合が発生した時のスクリーンショットやキャプチャー**
<video src="https://github.com/pantasystem/Milktea/assets/62137820/5eac07f0-8c46-48b2-b5f5-86513203eb59" />

**Comment by pantasystem** [comment]
2023.11.1からcwを空欄にすることができなくなったような気がしますね
バリデーション処理にバージョンのチェックおよびそれに応じたcwの内容のバリデーションを追加する必要性がありそうです

**Comment by pantasystem** [comment]
cwが有効かつ空欄の場合は何かしらの特殊文字をデフォルトで入れてしまうという方法もありますが、
cwの空欄が許可されなくなった理由を考えるとそれは微妙な気がします

**Comment by sanao1006** [comment]
バージョンもチェックも必要なのですねなるほど、、、

バリデーション処理を書き加える関数はこの関数であってますかね？
https://github.com/pantasystem/Milktea/blob/e8a85f29da67c05f2758a11cbd562954dfa997c8/modules/features/note/src/main/java/net/pantasystem/milktea/note/editor/viewmodel/NoteEditorUiState.kt#L61

ただ空かどうか判定するだけなら
```kotlin
if (this.formState.cw.isNullOrEmpty()) { return false }
```
これを書き加えればいけそうだとおもったのですが、バージョンのチェック方法が分からない状態です。

**Comment by sanao1006** [comment]
https://github.com/kanarikanaru/backspacekey/commit/ffa20911ed8cd91e066ae66d617aa71786c474ec

空チェックはminLengthを使う方法でもよいかもしれないですね

**Comment by pantasystem** [comment]
バージョンのチェック方法はcheckValidateにバージョンやソフトウェアの種別の情報を含むデータを
[InstanceInfoService](https://github.com/pantasystem/Milktea/blob/6a588b7477bca5cb71db8e4367f4c7468c594cd2/modules/model/src/main/java/net/pantasystem/milktea/model/instance/InstanceInfoService.kt#L19-L19)経由で取得して引数に渡すのが良いと思いました。
ただioとmisskey-dev/misskeyではバージョニング方式が異なるのが注意点ですね・・・

**Comment by pantasystem** [comment]
CWが空を許容するかをチェックするためのフィールドを追加しました。
当Issueですがアサインされますか？それとも私の方で修正した方がよろしいでしょうか？
https://github.com/pantasystem/Milktea/blob/ff0c613a41655a24fe0752324fcb01b6087d1ebb/modules/model/src/main/java/net/pantasystem/milktea/model/instance/InstanceInfoType.kt#L112-L112

**Comment by sanao1006** [comment]
ぜひ私に修正させてください。アサインの方、よろしくお願いします！

**Comment by sanao1006** [comment]
その前にひとつ質問があります

misskeyのバージョンチェック処理が必要だと思うのですが、バージョン11.1(でしたっけ？)以上であるかどうかの判定って
[Version](https://github.com/pantasystem/Milktea/blob/ff0c613a41655a24fe0752324fcb01b6087d1ebb/modules/model/src/main/java/net/pantasystem/milktea/model/instance/Version.kt) を使えばいいんでしょうか？

**Comment by pantasystem** [comment]
バージョンの判定にはおっしゃるとおりそのバージョンクラスを使用すればよいです。
ただ今回はあらかじめisCwAllowBlankを作成したので、isCwAllowBlankを使用すれば実装できると思います。
