### ISSUE TITLE
Follow button does not give feedback

### ISSUE THREAD

**Issue by lascimmia** [Kinoshita0623/MisskeyAndroidClient#255]
At least on profiles requiring to accept followers, when you press on follow button there's no feedback (like changing color or text)

![IMG_20210806_094715](https://user-images.githubusercontent.com/71778736/128476992-61ada647-4af5-416c-9330-4cb39f0da703.jpg)

**Comment by Kinoshita0623** [comment]
[ja]
次のアップデートで修正される予定です。
不具合の報告ありがとうございます！！

[en]
Bugs will be fixed in the next update!
Thank you for reporting!
