### ISSUE TITLE
めいすきーフォークにて新規登録ができない

### ISSUE THREAD

**Issue by xichedelic1337** [Kinoshita0623/MisskeyAndroidClient#91]
アクセスを許可を押してアプリに戻っても最初からやり直しになって使えない

**Comment by Kinoshita0623** [comment]
Milkteaは認可画面からMilkteaへのコールバックインテントを発行しないと最終認可処理を行わない実装になっています。
現在調査中なのですが、めいすきーの認可画面からコールバックインテントが発行されていない可能性が考えられます。
現在応急処置としてMilkteaの認可画面からユーザーが自発的に認可を完了したことをアプリ側に伝える実装をすることを検討しています。
